### ISSUE TITLE
The problem of Visualizations in RVIZ

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [cat722/mmdetection3d_ROS#1]
Excuse me.
What does this function do? pub_velo = rospy.Publisher("/modified", PointCloud2, queue_size=1)
When I visualize the kitti original point cloud with the original topic of "/kitti/velo/pointcloud" and the detection bboxes in RVIZ, the detection bboxes is somewhat off from the point cloud.
When I visualize with the topic of "/modified" the frame in RVIZ, there is no such problem!
Thank you!

**Comment by dlddllm** [comment]
> Excuse me. What does this function do? pub_velo = rospy.Publisher("/modified", PointCloud2, queue_size=1) When I visualize the kitti original point cloud with the original topic of "/kitti/velo/pointcloud" and the detection bboxes in RVIZ, the detection bboxes is somewhat off from the point cloud. When I visualize with the topic of "/modified" the frame in RVIZ, there is no such problem! Thank you!

After receiving the point cloud information, the detection takes time, so the detection frame does not match the point cloud of the current display frame.Therefore, after the detection box result is obtained, the current frame point cloud information is re-published.it is "/modified"

**Comment by RhythmOfTheRain-Byte** [comment]
> > Excuse me. What does this function do? pub_velo = rospy.Publisher("/modified", PointCloud2, queue_size=1) When I visualize the kitti original point cloud with the original topic of "/kitti/velo/pointcloud" and the detection bboxes in RVIZ, the detection bboxes is somewhat off from the point cloud. When I visualize with the topic of "/modified" the frame in RVIZ, there is no such problem! Thank you!
> 
> @RhythmOfTheRain-Byte receiving the point cloud information, the detection takes time, so the detection frame does not match the point cloud of the current display frame.Therefore, after the detection box result is obtained, the current frame point cloud information is re-published.it is "/modified"

Thank you for your answer! I will try it again.

**Comment by RhythmOfTheRain-Byte** [comment]
> > Excuse me. What does this function do? pub_velo = rospy.Publisher("/modified", PointCloud2, queue_size=1) When I visualize the kitti original point cloud with the original topic of "/kitti/velo/pointcloud" and the detection bboxes in RVIZ, the detection bboxes is somewhat off from the point cloud. When I visualize with the topic of "/modified" the frame in RVIZ, there is no such problem! Thank you!
> 
> @RhythmOfTheRain-Byte receiving the point cloud information, the detection takes time, so the detection frame does not match the point cloud of the current display frame.Therefore, after the detection box result is obtained, the current frame point cloud information is re-published.it is "/modified"

     

Thank you for your answer! I will try it again.
