### ISSUE TITLE
无法检测出目标

### ISSUE THREAD

**Issue by zhangzirui1998** [cat722/mmdetection3d_ROS#2]
请问你是用kitti的rosbag测试的吗，我用ouster雷达的rosbag数据检测不出来，是因为数据问题吗？
这个是rosbag的下载地址https://drive.google.com/drive/folders/1EFMqNyYWhlLeew4jQkHutBEgnGz9naOK?usp=sharing

**Comment by cat722** [comment]
@zhangzirui1998 可以在回调函数中更改数据接收方式，改为points = np.array(pc2.read_points_list(msg, field_names = ("x", "y", "z","intensity"), skip_nans=True))，同时别忘了将“instensity”这一维度置0。
